language: ruby

install:
  - gem install bundler 
  - bundle install
cache:
  bundler: true 

env:
  global:
    # RUBYGEMS_KEY - API key to publish to rubygems. 

jobs:
  include:
    - stage: danger
      script: bundle exec danger --fail-on-errors=true
    - stage: tests      
      script: bundle exec rake lint    
    - # tests 
      script: bundle exec rake install && bundle exec dotenv-android -v
    - stage: deploy
      script: 
        - printf "%s\\n%s " "---" ":rubygems_api_key:" > ~/.gem/credentials
        - printf $RUBYGEMS_KEY >> ~/.gem/credentials
        - chmod 0600 ~/.gem/credentials
        - bundle exec rake publish

stages:
  - name: danger
    if: type IN (pull_request)
  - name: tests
    if: type IN (push, pull_request) AND tag IS blank
  - name: deploy
    if: tag IS present